# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: newkey
      ImageId: ami-08c40ec9ead489470
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0