version: 2.1
orbs:
    aws-cli: circleci/aws-cli@2.0.3
jobs:                
# Exercise: Config and Deployment
    configure_infrastructure: 
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["1b:d2:da:64:85:ce:ae:7d:be:50:b9:9b:ce:6e:0e:98"] 
            - run:
                name: Install Ansible
                command: |
                    apk add --update ansible
            - run:
                name: Run Playbook and Configure server
                command: |
                    ansible-playbook -i inventory main-remote.yml

workflows:
    myWorkflow:
        jobs:
            - configure_infrastructure:
            